name: 'Name'
inputs:
  name:
    description: 'Some value'
    type: string
    default: 'wiscussy'

outputs:
  greet-text:
    value: ${{ steps.greet.outputs.greet_text }}

runs:
  using: "composite"
  steps:
    - name: Swoooosh
      id: greet
      run: |
        GREET_TEXT='Hello. ${{ inputs.name }}
        echo $GREET_TEXT >> $GITHUB_STEP_SUMMARY
        echo "greet_text=$GREET_TEXT" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/setup-node@v3

