name: 'Name'
inputs:
  name:
    description: 'Some value'
    type: string
    default: 'wiscussy'

outputs:
  greet-text:
    value: ${{ steps.greet.outputs.greet_text }}

runs:
  using: "composite"
  steps:
    - name: Swoooosh
      id: greet
      run: echo "greet_text='Hello. ${{ inputs.name }}'" >> $GITHUB_OUTPUT

