---
name: Use composite action
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to greet"
        required: true
        default: "wiscussy"
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Swooooosh
        id: composite
        uses: ./.github/actions/composite-test
        with:
          name: ${{ inputs.name }}
      - name: Print output
        run: echo ${{ steps.composite.output.greet-text }}
